# Generated by Django 2.0.6 on 2018-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=500)),
                ('agg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
