# Generated by Django 2.0.6 on 2018-10-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=4096)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('group_no', models.IntegerField(default=0)),
                ('order_no', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
    ]
